name: "HTML Validator for test_app"
on:
  push:
    branches: ["main"]
jobs:
  validator:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Clone repo
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'main'
          owner: 'sdnv0x4d'
          repository: 'test_app'
      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@master
        with:
          root: html/